services:
  backend:
    platform: linux/arm64
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pdfs:/app/pdfs
    environment:
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  frontend:
    platform: linux/arm64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pdfs:
